### ISSUE TITLE
Exporting Consensus Sequence snafu

### ISSUE THREAD

**Issue by arturo79** [veg/HIV-NGS#10]
When attempting to 'Export Consensus Sequences' from ProtC data (>1000 records), it only captured 133 sequences. Looking at individual datasets that were not captured in the export revealed no significant problems; I was able to generate a consensus sequence myself from them. 
Thanks!
Gabe

**Comment by spond** [comment]
Resolved via 148eaa948e4262504c7934f314f221021cba9198 and 9a3e05687cf078cc0e84d8d3e980e77b232f4987 in https://github.com/spond/
